name: Send notification on release created

on:
  release:
    types: [published]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo github.event.release.url
          echo github.event.release.tag_name
