name: Send notification on release created

on:
  release:
    types: [published]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: notify
        run: |
          echo github.event.release.uploadurl
          echo github.event.release.tag_name
